logging:
  level:
    root: debug
    
    
server:
  servlet:
    context-path: /learning-simple
    
    
info:
  app:
    name: Actuator learning app
    description: Learning all the Production ready features of the spring-boot-actuator
    version: 0.0.1-SNAPSHOT
    

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
      


    
